// AUTO-GENERATED by scripts/sync-seo-meta.mjs — do not edit by hand
window.__MRBILL_SEO_CONFIG__ = {
  "site": {
    "origin": "https://mrbill-dev.github.io",
    "siteName": "Mr.Bill 數位實驗室",
    "locale": "zh_TW",
    "lang": "zh-Hant",
    "titleSuffix": "Mr.Bill 數位實驗室",
    "defaultDescription": "Mr.Bill 數位實驗室整理 AI 應用、前端網頁設計、攝影視覺、內容表達與 SEO/GEO 實戰教學，適合學生、家長、自學者與創作者建立可交付的數位能力。",
    "defaultOgImage": "images/og-home.jpg",
    "defaultOgImageWidth": 1200,
    "defaultOgImageHeight": 630,
    "defaultOgImageAlt": "Mr.Bill 數位實驗室 AI 前端 攝影 SEO 學習平台",
    "twitterCard": "summary_large_image",
    "organization": {
      "@context": "https://schema.org",
      "@type": "EducationalOrganization",
      "name": "Mr.Bill 數位實驗室",
      "description": "Mr.Bill 數位實驗室提供 AI 應用、前端網頁設計、攝影視覺、內容表達與 SEO/GEO 實戰教學。",
      "sameAs": [],
      "knowsAbout": [
        "AI 教學",
        "Prompt Engineering",
        "前端網頁設計",
        "HTML",
        "CSS",
        "JavaScript",
        "攝影教學",
        "SEO",
        "GEO",
        "內容表達"
      ]
    }
  },
  "pages": {
    "home": {
      "path": "/",
      "title": "Mr.Bill 數位實驗室｜AI 教學、前端設計、攝影與 SEO 實戰學習",
      "description": "Mr.Bill 數位實驗室整理 AI 應用、前端網頁設計、攝影視覺、內容表達與 SEO/GEO 實戰教學，適合學生、家長、自學者與創作者建立可交付的數位能力。",
      "ogTitle": "Mr.Bill 數位實驗室｜AI、前端、攝影與 SEO 實戰學習",
      "ogDescription": "從 AI 基礎、Prompt、前端網頁、攝影視覺到 SEO/GEO，建立能實作、能交付、能被搜尋的數位學習路徑。",
      "ogImage": "images/og-home.jpg",
      "ogImageAlt": "Mr.Bill 數位實驗室 AI 前端 攝影 SEO 學習平台",
      "twitterDescription": "AI 應用、Prompt、前端網頁、攝影視覺、內容表達與 SEO/GEO 實戰學習入口。",
      "type": "website",
      "rawTitle": true,
      "jsonLd": true
    },
    "tutorial": {
      "title": "前端與設計手冊",
      "description": "HTML、CSS、JavaScript 與 RWD 實作教學，含互動沙盒、作業檢核與從零到可上線的前端學習路徑。",
      "type": "website"
    },
    "photography": {
      "title": "攝影光影練習室｜曝光、構圖、焦段、白平衡與後製互動教學",
      "description": "攝影光影練習室以互動方式練習曝光三角、構圖、焦段、白平衡、RAW/JPG、閃燈同步、光質軟硬與剪映後製流程，幫助新手理解相機參數與畫面質感的關係。",
      "ogTitle": "攝影光影練習室｜曝光、構圖、焦段、白平衡與後製互動教學",
      "ogDescription": "攝影光影練習室以互動方式練習曝光三角、構圖、焦段、白平衡、RAW/JPG、閃燈同步、光質軟硬與剪映後製流程，幫助新手理解相機參數與畫面質感的關係。",
      "rawTitle": true,
      "type": "website"
    },
    "ai-learning-map": {
      "title": "AI 學習地圖｜從 Prompt 到 Agent、RAG、前端開發與影像應用",
      "description": "Mr.Bill AI 學習地圖，從 AI 新手入門、Prompt 工程、RAG、Agent、自動化、前端開發、影像生成到 SEO/GEO 實戰，建立可交付的 AI 工作流程。",
      "ogTitle": "AI 學習地圖｜從 Prompt 到 Agent、RAG、前端開發與影像應用",
      "ogDescription": "從 AI 新手入門、Prompt 工程、RAG、Agent 到前端開發與 SEO/GEO，建立可交付的 AI 工作流程。",
      "rawTitle": true,
      "type": "website"
    },
    "ai-practice": {
      "title": "AI 互動練習箱｜Prompt 練習、AI 概念題與新手任務",
      "description": "透過 AI 互動練習題、概念解析、Prompt 帶練步驟與實戰任務，幫助新手理解 AI、查證回答，並把 AI 產出轉成可交付成果。",
      "ogTitle": "AI 互動練習箱｜Prompt 練習、AI 概念題與新手任務",
      "ogDescription": "透過 AI 互動練習題、概念解析、Prompt 帶練步驟與實戰任務，幫助新手理解 AI、查證回答，並把 AI 產出轉成可交付成果。",
      "rawTitle": true,
      "type": "website"
    },
    "ai-prompt-tool": {
      "title": "Prompt 指令工具箱｜AI Prompt 模板、Markdown 指令與工作流產生器",
      "description": "使用 Prompt 指令工具箱，從應用情境、角色、任務、背景、限制、輸出格式與語氣快速產生可複製的 Markdown Prompt，適合教學、前端、行銷、影像與工作流程應用。",
      "type": "website"
    },
    "ai-game-center": {
      "title": "AI 小遊戲中心｜用闖關方式練 Prompt、工具選擇與 AI 判斷力",
      "description": "AI 小遊戲中心透過任務闖關、情境決策、工具選擇、限時挑戰與雙人協作，幫助新手練習 Prompt、AI 查證、任務拆解與可交付成果整理。",
      "type": "website"
    },
    "ai-workshop-playbook": {
      "title": "AI 實戰教學總覽",
      "description": "工作坊教案、教學流程與實戰模組總覽，協助教學與自學規劃。",
      "type": "website"
    },
    "design-toolkit": {
      "title": "視覺設計學院",
      "description": "版面、色彩、字體與 UI 實作工具箱，連結設計思維與前端落地。",
      "type": "website"
    },
    "geo-content-lab": {
      "title": "內容表達學：網站文案到簡報",
      "description": "從網站文案、簡報到影片腳本，建立能被理解與被搜尋的內容表達能力。",
      "type": "website"
    },
    "marketing-seo-geo": {
      "title": "SEO / GEO 與 GA4 實戰",
      "description": "搜尋優化、生成式引擎優化與 GA4 事件追蹤實戰，附檢查表與可落地步驟。",
      "type": "website"
    },
    "blog-index": {
      "path": "/blog/",
      "title": "文章筆記｜實務經驗、數位工作與生活觀察",
      "description": "Mr.Bill 的文章筆記，整理 AI、前端、設計、攝影、SEO、工作流、教學與生活觀察，分享工作與學習中累積的實務經驗與可參考做法。",
      "ogTitle": "文章筆記｜實務經驗、數位工作與生活觀察",
      "ogDescription": "Mr.Bill 的文章筆記，整理 AI、前端、設計、攝影、SEO、工作流、教學與生活觀察，分享工作與學習中累積的實務經驗與可參考做法。",
      "ogImage": "assets/blog-index-hero.jpg",
      "ogImageAlt": "文章筆記與實務整理的工作坊討論情境",
      "rawTitle": true,
      "type": "website"
    }
  }
};
